INSERT INTO user (email, name, password) VALUES ('a@a.a', 'dpudpu', '1234');
INSERT INTO user (email, name, password) VALUES ('a@a.ab', 'dpudpud', '1234');
INSERT INTO user (email, name, password) VALUES ('a@a.ac', 'dpudpua', '1234');
INSERT INTO user (email, name, password) VALUES ('a@a.ad', 'dpudpux', '1234');
INSERT INTO user (email, name, password) VALUES ('a@a.ae', 'fdpudpu', '1234');
INSERT INTO user (email, name, password) VALUES ('a@a.af', 'edpudpu', '1234');
INSERT INTO user (email, name, password) VALUES ('a@a.ah', 'dpudpu', '1234');
INSERT INTO user (email, name, password) VALUES ('ab@a.a', 'chulsea', '1234');
INSERT INTO user (email, name, password) VALUES ('ac@a.a', 'olaf', '1234');
INSERT INTO user (email, name, password) VALUES ('도넛@woowa.com', '도넛', '6236c5d0');
INSERT INTO user (email, name, password) VALUES ('아이크@woowa.com', '아이크', 'ecb0aace');
INSERT INTO user (email, name, password) VALUES ('미스터코@woowa.com', '미스터코', '3214235c');
INSERT INTO user (email, name, password) VALUES ('루피@woowa.com', '루피', '09ea5f02');
INSERT INTO user (email, name, password) VALUES ('로비@woowa.com', '로비', 'c63226a5');
INSERT INTO user (email, name, password) VALUES ('러너덕@woowa.com', '러너덕', '4babbc0a');
INSERT INTO user (email, name, password) VALUES ('규동@woowa.com', '규동', 'a68fbad0');
INSERT INTO user (email, name, password) VALUES ('뚱이@woowa.com', '뚱이', '7279e0de');
INSERT INTO user (email, name, password) VALUES ('이바@woowa.com', '이바', 'ea4ea626');
INSERT INTO user (email, name, password) VALUES ('안돌@woowa.com', '안돌', 'e59c7344');
INSERT INTO user (email, name, password) VALUES ('무민@woowa.com', '무민', 'f6d35f20');
INSERT INTO user (email, name, password) VALUES ('제이엠@woowa.com', '제이엠', '1779e1f6');
INSERT INTO user (email, name, password) VALUES ('이지@woowa.com', '이지', '850e79f3');
INSERT INTO user (email, name, password) VALUES ('희봉@woowa.com', '희봉', '0385fb61');
INSERT INTO user (email, name, password) VALUES ('쿠기@woowa.com', '쿠기', 'f27c30c5');
INSERT INTO user (email, name, password) VALUES ('효오@woowa.com', '효오', '9df13868');
INSERT INTO user (email, name, password) VALUES ('버디@woowa.com', '버디', 'b59f8717');
INSERT INTO user (email, name, password) VALUES ('슬로스@woowa.com', '슬로스', '0d2aea82');
INSERT INTO user (email, name, password) VALUES ('철시@woowa.com', '철시', '251e1a5b');
INSERT INTO user (email, name, password) VALUES ('코맥@woowa.com', '코맥', '5dbcb4ec');
INSERT INTO user (email, name, password) VALUES ('김고래@woowa.com', '김고래', '909d60a6');
INSERT INTO user (email, name, password) VALUES ('닉@woowa.com', '닉', 'a35fb2c0');
INSERT INTO user (email, name, password) VALUES ('제이@woowa.com', '제이', '17112b8e');
INSERT INTO user (email, name, password) VALUES ('에헴@woowa.com', '에헴', '5033d59f');
INSERT INTO user (email, name, password) VALUES ('쉐이크반@woowa.com', '쉐이크반', 'c0f26894');
INSERT INTO user (email, name, password) VALUES ('베디@woowa.com', '베디', 'a8f29945');
INSERT INTO user (email, name, password) VALUES ('올라프@woowa.com', '올라프', 'acd80402');
INSERT INTO user (email, name, password) VALUES ('코나스@woowa.com', '코나스', 'f5b09b4d');
INSERT INTO user (email, name, password) VALUES ('션@woowa.com', '션', '5c7f58ff');
INSERT INTO user (email, name, password) VALUES ('히브리@woowa.com', '히브리', 'b4f229f4');
INSERT INTO user (email, name, password) VALUES ('에단@woowa.com', '에단', 'db7bc193');
INSERT INTO user (email, name, password) VALUES ('르윈@woowa.com', '르윈', '629ef1e8');
INSERT INTO user (email, name, password) VALUES ('유니@woowa.com', '유니', '0612ce3b');
INSERT INTO user (email, name, password) VALUES ('던@woowa.com', '던', 'a165af92');
INSERT INTO user (email, name, password) VALUES ('미르@woowa.com', '미르', '65d59697');
INSERT INTO user (email, name, password) VALUES ('해리@woowa.com', '해리', '40177968');
INSERT INTO user (email, name, password) VALUES ('티버@woowa.com', '티버', 'f0918ba3');
INSERT INTO user (email, name, password) VALUES ('포도당@woowa.com', '포도당', '97a40d87');
INSERT INTO user (email, name, password) VALUES ('마틴@woowa.com', '마틴', 'a272aff7');
INSERT INTO user (email, name, password) VALUES ('지노@woowa.com', '지노', '39feb9ce');
INSERT INTO user (email, name, password) VALUES ('에이든@woowa.com', '에이든', 'f2e94d8c');
INSERT INTO user (email, name, password) VALUES ('큰곰@woowa.com', '큰곰', '5dd37533');
INSERT INTO user (email, name, password) VALUES ('비모@woowa.com', '비모', '191e9d41');
INSERT INTO user (email, name, password) VALUES ('코니@woowa.com', '코니', '87e78ef8');
INSERT INTO user (email, name, password) VALUES ('올레@woowa.com', '올레', '44deaf34');
INSERT INTO user (email, name, password) VALUES ('포비@woowa.com', '포비', '31d2dc63');
INSERT INTO user (email, name, password) VALUES ('브라운@woowa.com', '브라운', 'd6f9388a');
INSERT INTO user (email, name, password) VALUES ('씨유@woowa.com', '씨유', '932ab6ae');
INSERT INTO user (email, name, password) VALUES ('제이슨@woowa.com', '제이슨', '7457d0f8');
INSERT INTO user (email, name, password) VALUES ('준@woowa.com', '준', '30ecdc97');
INSERT INTO user (email, name, password) VALUES ('워니@woowa.com', '워니', '26dbc0db');

INSERT INTO post (contents, author_id, created_at, updated_at) VALUES ('contents', 1, '2019-01-31 23:59:59', '2019-08-12 23:59:59');
INSERT INTO post (contents, author_id, created_at) VALUES ('contents', 1, '2019-01-31 23:59:59');

INSERT INTO comment(contents, user_id, post_id, created_at, updated_at) VALUES ('comment1', 1, 1, '2019-08-21 08:31:25', '2019-08-21 12:31:25');
INSERT INTO comment(contents, user_id, post_id, created_at, updated_at) VALUES ('comment2', 1, 1, '2019-08-21 08:31:25', '2019-08-21 08:31:25');
INSERT INTO comment(contents, user_id, post_id, created_at, updated_at) VALUES ('comment3', 1, 1, '2019-08-19 08:31:25', '2019-08-19 08:31:25');
INSERT INTO comment(contents, user_id, post_id, created_at, updated_at) VALUES ('comment4', 1, 1, '2019-07-12 08:31:25', '2019-07-12 08:31:25');

INSERT INTO comment(contents, user_id, post_id, parent_id) VALUES ('comment4', 1, 1, 1);
INSERT INTO comment(contents, user_id, post_id, parent_id) VALUES ('comment5', 1, 1, 1);