CREATE TABLE if NOT EXISTS video(
	id BIGINT AUTO_INCREMENT,
	youtube_id VARCHAR(255) NOT NULL,
	title VARCHAR(100) NOT NULL,
	contents TEXT NOT NULL,
	create_date DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
);
